@isTest
private class Test_sapComDocumentSapRfcFunctions {

    static testMethod void testsapComDocumentSapRfcFunctions() {
      sapComDocumentSapRfcFunctions.BAPISOLDTO sap = new sapComDocumentSapRfcFunctions.BAPISOLDTO();
      sapComDocumentSapRfcFunctions.ORDER_CFGS_PART_OF_element CFGS = new sapComDocumentSapRfcFunctions.ORDER_CFGS_PART_OF_element();
      sapComDocumentSapRfcFunctions.ORDER_ITEMS_OUT_element item = new sapComDocumentSapRfcFunctions.ORDER_ITEMS_OUT_element();
      sapComDocumentSapRfcFunctions.BAPICUINS ins = new sapComDocumentSapRfcFunctions.BAPICUINS();
      sapComDocumentSapRfcFunctions.BAPICCARD sap9 = new sapComDocumentSapRfcFunctions.BAPICCARD();
      sapComDocumentSapRfcFunctions.NFMETALLITMS_IM_element sap10 = new sapComDocumentSapRfcFunctions.NFMETALLITMS_IM_element();
      sapComDocumentSapRfcFunctions.BAPICUPRT sap11 = new sapComDocumentSapRfcFunctions.BAPICUPRT();
     
      sapComDocumentSapRfcFunctions.BAPISCHDL sap13 = new sapComDocumentSapRfcFunctions.BAPISCHDL();
      sapComDocumentSapRfcFunctions.ORDER_SCHEDULE_IN_element sap14 = new sapComDocumentSapRfcFunctions.ORDER_SCHEDULE_IN_element();
      sapComDocumentSapRfcFunctions.BAPICUBLB sap15 = new sapComDocumentSapRfcFunctions.BAPICUBLB();
     
      sapComDocumentSapRfcFunctions.BAPIITEMEX sap17 = new sapComDocumentSapRfcFunctions.BAPIITEMEX();
      sapComDocumentSapRfcFunctions.ORDER_CFGS_INST_element sap18 = new sapComDocumentSapRfcFunctions.ORDER_CFGS_INST_element();
      sapComDocumentSapRfcFunctions.MESSAGETABLE_element sap19 = new sapComDocumentSapRfcFunctions.MESSAGETABLE_element();
     
      sapComDocumentSapRfcFunctions.ORDER_CFGS_BLOB_element sap21 = new sapComDocumentSapRfcFunctions.ORDER_CFGS_BLOB_element();
      sapComDocumentSapRfcFunctions.BAPIPAREX sap22 = new sapComDocumentSapRfcFunctions.BAPIPAREX();
      sapComDocumentSapRfcFunctions.EXTENSIONIN_element sap23 = new sapComDocumentSapRfcFunctions.EXTENSIONIN_element();
     
      sapComDocumentSapRfcFunctions.BAPIINCOMP sap25 = new sapComDocumentSapRfcFunctions.BAPIINCOMP();
      sapComDocumentSapRfcFunctions.BAPICCARD_EX sap26 = new sapComDocumentSapRfcFunctions.BAPICCARD_EX();
      sapComDocumentSapRfcFunctions.BAPICUVAL sap30 = new sapComDocumentSapRfcFunctions.BAPICUVAL();
     
      sapComDocumentSapRfcFunctions.ORDER_CFGS_REF_element sap31 = new sapComDocumentSapRfcFunctions.ORDER_CFGS_REF_element();
      sapComDocumentSapRfcFunctions.BAPISDHEDU sap32 = new sapComDocumentSapRfcFunctions.BAPISDHEDU();
      sapComDocumentSapRfcFunctions.BAPIADDR1 sap33 = new sapComDocumentSapRfcFunctions.BAPIADDR1();
     
     
      sapComDocumentSapRfcFunctions.x_xNFM_xBAPIDOCITM sap34 = new sapComDocumentSapRfcFunctions.x_xNFM_xBAPIDOCITM();
      sapComDocumentSapRfcFunctions.ORDER_CFGS_VALUE_element sap35 = new sapComDocumentSapRfcFunctions.ORDER_CFGS_VALUE_element();
      sapComDocumentSapRfcFunctions.BAPIRET2 sap36 = new sapComDocumentSapRfcFunctions.BAPIRET2();
     
      sapComDocumentSapRfcFunctions.ORDER_CCARD_element sap38 = new sapComDocumentSapRfcFunctions.ORDER_CCARD_element();
      sapComDocumentSapRfcFunctions.BAPICUCFG sap39 = new sapComDocumentSapRfcFunctions.BAPICUCFG();
      sapComDocumentSapRfcFunctions.PARTNERADDRESSES_element sap40 = new sapComDocumentSapRfcFunctions.PARTNERADDRESSES_element();
     
     
      sapComDocumentSapRfcFunctions.NFMETALLITMS_EX_element sap43 = new sapComDocumentSapRfcFunctions.NFMETALLITMS_EX_element();
      sapComDocumentSapRfcFunctions.BAPISHIPTO sap44 = new sapComDocumentSapRfcFunctions.BAPISHIPTO();
      sapComDocumentSapRfcFunctions.ORDER_INCOMPLETE_element sap46 = new sapComDocumentSapRfcFunctions.ORDER_INCOMPLETE_element();
     
      sapComDocumentSapRfcFunctions.ORDER_SCHEDULE_EX_element sap47 = new sapComDocumentSapRfcFunctions.ORDER_SCHEDULE_EX_element ();
      sapComDocumentSapRfcFunctions.BAPIPAYER sap48 = new sapComDocumentSapRfcFunctions.BAPIPAYER ();
      sapComDocumentSapRfcFunctions.ORDER_CCARD_EX_element sap49 = new sapComDocumentSapRfcFunctions.ORDER_CCARD_EX_element ();
      
      salesforceComQuote.ExchangeFaultData data1 = new salesforceComQuote.ExchangeFaultData();
      salesforceComQuote.ExchangeLogData data2 = new salesforceComQuote.ExchangeLogData(); 
      salesforceComQuote.SFDC_Quote_Fault_MT_element data3 = new salesforceComQuote.SFDC_Quote_Fault_MT_element(); 
    }
}